### ISSUE TITLE
Double messages

### ISSUE THREAD

**Issue by Marilyth** [Marilyth/MopsBot-1.0#16]
Mops sends twitvh notifications and twitter notifications twice or even thrice, i dont know what causes this at all.
We should fix this.

**Comment by Togira-Ikonoka** [comment]
Added Console out when TwitchTracker object created and when Channel added

**Comment by Marilyth** [comment]
In case it is some kind of thread duplication, we will need another way to track the bug.

**Comment by Marilyth** [comment]
Happens due to onClientReady in Program.cs
@Togira-Ikonoka

**Comment by Marilyth** [comment]
Seems to have stopped.
Will reopen if happens again
