### ISSUE TITLE
TwitchTracker average stats at the end of a livestream

### ISSUE THREAD

**Issue by Marilyth** [Marilyth/MopsBot-1.0#9]
Mops should be able to collect and evaluate data such as viewer count and determine the mean of it throughout the whole stream, to show the results at the end of the stream.
He should also determine the viewer peak as well as the game during which it occured.

Maybe you could plot it all and paste an image instead? (I don't know how or if that works)

**Comment by Togira-Ikonoka** [comment]
Maybe oxyplot for plotting

**Comment by Marilyth** [comment]
Done
